services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install && npm run dev -- --host"